# Template for config file /etc/klish/klishd.conf. It's used by klishd daemon.

# The klishd uses UNIX domain socket to receive connections. It will create an
# filesystem entry to allow clients to find connection point. By default klishd
# uses /tmp/klish-unix-socket path.
#UnixSocketPath=/tmp/klish-unix-socket

# The created listening UNIX domain socket can be "chown"-ed to the specified
# user and group. By default klishd will not perform "chown".
#UnixSocketUser=klish
#UnixSocketGroup=klish

# The created listening UNIX domain socket can be "chmod"-ed to the specified
# value. By default klishd will not perform "chmod".
#UnixSocketMode=0755


DBs=libxml2
DB.libxml2.XMLPath=/home/pkun/work/klish/examples/simple
